disableIdentityWidgetInjection: true
backend:
  name: git-gateway
  branch: main
media_folder: src/assets/images/
public_folder: _astro/
collections:
  - name: drinks
    label: Drinks
    folder: src/content/drinks
    create: true
    delete: true
    fields:
      - name: title
        widget: string
        label: Menu Item Name
      - name: image
        widget: image
        label: Image
      - name: body
        widget: markdown
        label: Drink Description
  - name: performances
    label: Upcoming Performances
    folder: src/content/performances
    create: true
    delete: true
    fields:
      - name: title
        widget: string
        label: Performance Title
      - name: image
        widget: image
        label: Promotional Image
        required: false
      - name: body
        widget: markdown
        label: Concert Description
      - name: date
        widget: datetime
        label: Performance Date
