disableIdentityWidgetInjection: true
backend:
  name: git-gateway
  branch: master
media_folder: src/assets/images/
public_folder: _astro/
collections:
  - name: performances
    label: Performances
    folder: src/content/performances
    create: true
    delete: true
    fields:
      - name: title
        widget: string
        label: Performance Title
      - name: date
        widget: datetime
        date_format: MMMM D, YYYY
        label: Performance Date
      - name: startTime
        widget: datetime
        time_format: "HH:mm"
        label: Performance Start Time
      - name: endTime
        widget: datetime
        time_format: "HH:mm"
        label: Performance End Time
      - name: isTicketLink
        widget: boolean
        label: Show a button with a link
        required: false
      - name: body
        widget: markdown
        label: Concert Description
        required: false
  - name: banner
    label: Banner 
    folder: src/content/banner
    create: false
    delete: false
    fields:
      - name: title 
        widget: string
        label: Banner Title(unused)
      - name: isBannerActive
        widget: boolean
        label: Show the Banner?
      - name: body
        widget: markdown
        label: Banner Message