disableIdentityWidgetInjection: true
backend:
  name: git-gateway
  branch: master
media_folder: src/assets/images/
public_folder: _astro/
collections:
  - name: performances
    label: Performances
    folder: src/content/performances
    create: true
    delete: true
    fields:
      - name: title
        widget: string
        label: Performance Title
      - name: date
        widget: datetime
        label: Performance Date
      - name: image
        widget: image
        label: Promotional Image
        required: false
      - name: body
        widget: markdown
        label: Concert Description
        required: false
  - name: banner
    label: Banner 
    folder: src/content/banner
    create: false
    delete: false
    fields:
      - name: isBannerActive
        widget: boolean
        label: Show the Banner?
      - name: body
        widget: markdown
        label: Banner Message